language: node_js
node_js:
- '10'
addons:
  sonarqube:
    organization: "omar97perez-github"
    token:
        secure: 1b0b6f2e19a6e3460df039f31900fe75e30af937

sudo: false
branches:
  only:
  - master
script:
- cd app
- npm install
- npm test
- sonar-scanner
cache:
  directories:
  - node_modules
