language: node_js
node_js:
- '10'
addons:
  sonarqube:
    organization: "sytw12018"
    token:
        secure: 4cccb2af3ec8fa877bb1d36376fb14a02e0121a9

sudo: false
branches:
  only:
  - master
script:
- cd app
- npm install
- npm test
- cd ..
- npm install sonar-scanner
- sonar-scanner
cache:
  directories:
  - node_modules
